name: Sync to Hugging Face Hub

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Hugging Face Hub SDK
        run: |
          pip install --upgrade huggingface_hub

      - name: Sync to Hugging Face Space via HF CLI
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: "musashivulpix"
          SPACE_NAME: "realtime-traffic-analytics-pipeline"
        run: |
          hf upload $HF_USERNAME/$SPACE_NAME . . --repo-type=space --token=$HF_TOKEN --delete="*"